//go:build !ignore_autogenerated

/*
Copyright 2026 NVIDIA

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.Taint != nil {
		in, out := &in.Taint, &out.Taint
		*out = new(corev1.Taint)
		(*in).DeepCopyInto(*out)
	}
	if in.NoEffect != nil {
		in, out := &in.NoEffect, &out.NoEffect
		*out = new(bool)
		**out = **in
	}
	if in.CustomLabel != nil {
		in, out := &in.CustomLabel, &out.CustomLabel
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Drain != nil {
		in, out := &in.Drain, &out.Drain
		*out = new(bool)
		**out = **in
	}
	if in.CustomAction != nil {
		in, out := &in.CustomAction, &out.CustomAction
		*out = new(string)
		**out = **in
	}
	if in.Hold != nil {
		in, out := &in.Hold, &out.Hold
		*out = new(bool)
		**out = **in
	}
	if in.Force != nil {
		in, out := &in.Force, &out.Force
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.LastStartupTime != nil {
		in, out := &in.LastStartupTime, &out.LastStartupTime
		*out = (*in).DeepCopy()
	}
	if in.InitialBootID != nil {
		in, out := &in.InitialBootID, &out.InitialBootID
		*out = new(string)
		**out = **in
	}
	if in.RebootMethod != nil {
		in, out := &in.RebootMethod, &out.RebootMethod
		*out = new(RebootMethodType)
		**out = **in
	}
	if in.LastObservedPendingNVConfig != nil {
		in, out := &in.LastObservedPendingNVConfig, &out.LastObservedPendingNVConfig
		*out = new(PendingNVConfigState)
		(*in).DeepCopyInto(*out)
	}
	if in.RebootSequenceCount != nil {
		in, out := &in.RebootSequenceCount, &out.RebootSequenceCount
		*out = new(int32)
		**out = **in
	}
	if in.KubeletVersion != nil {
		in, out := &in.KubeletVersion, &out.KubeletVersion
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFB) DeepCopyInto(out *BFB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFB.
func (in *BFB) DeepCopy() *BFB {
	if in == nil {
		return nil
	}
	out := new(BFB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BFB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFBList) DeepCopyInto(out *BFBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BFB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFBList.
func (in *BFBList) DeepCopy() *BFBList {
	if in == nil {
		return nil
	}
	out := new(BFBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BFBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFBReference) DeepCopyInto(out *BFBReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFBReference.
func (in *BFBReference) DeepCopy() *BFBReference {
	if in == nil {
		return nil
	}
	out := new(BFBReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFBSpec) DeepCopyInto(out *BFBSpec) {
	*out = *in
	if in.FileName != nil {
		in, out := &in.FileName, &out.FileName
		*out = new(string)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = new(BFBVersions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFBSpec.
func (in *BFBSpec) DeepCopy() *BFBSpec {
	if in == nil {
		return nil
	}
	out := new(BFBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFBStatus) DeepCopyInto(out *BFBStatus) {
	*out = *in
	out.Versions = in.Versions
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFBStatus.
func (in *BFBStatus) DeepCopy() *BFBStatus {
	if in == nil {
		return nil
	}
	out := new(BFBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFBVersions) DeepCopyInto(out *BFBVersions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFBVersions.
func (in *BFBVersions) DeepCopy() *BFBVersions {
	if in == nil {
		return nil
	}
	out := new(BFBVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueFieldSoftware) DeepCopyInto(out *BlueFieldSoftware) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueFieldSoftware.
func (in *BlueFieldSoftware) DeepCopy() *BlueFieldSoftware {
	if in == nil {
		return nil
	}
	out := new(BlueFieldSoftware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueFieldSoftware) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueFieldSoftwareList) DeepCopyInto(out *BlueFieldSoftwareList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlueFieldSoftware, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueFieldSoftwareList.
func (in *BlueFieldSoftwareList) DeepCopy() *BlueFieldSoftwareList {
	if in == nil {
		return nil
	}
	out := new(BlueFieldSoftwareList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueFieldSoftwareList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueFieldSoftwareStatus) DeepCopyInto(out *BlueFieldSoftwareStatus) {
	*out = *in
	out.Versions = in.Versions
	out.DownloadedComponents = in.DownloadedComponents
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueFieldSoftwareStatus.
func (in *BlueFieldSoftwareStatus) DeepCopy() *BlueFieldSoftwareStatus {
	if in == nil {
		return nil
	}
	out := new(BlueFieldSoftwareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueFieldSpec) DeepCopyInto(out *BlueFieldSpec) {
	*out = *in
	if in.TmpFwComponents != nil {
		in, out := &in.TmpFwComponents, &out.TmpFwComponents
		*out = new(TmpFwComponents)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueFieldSpec.
func (in *BlueFieldSpec) DeepCopy() *BlueFieldSpec {
	if in == nil {
		return nil
	}
	out := new(BlueFieldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BluefieldSoftwareVersions) DeepCopyInto(out *BluefieldSoftwareVersions) {
	*out = *in
	out.TmpFwComponentsVersions = in.TmpFwComponentsVersions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BluefieldSoftwareVersions.
func (in *BluefieldSoftwareVersions) DeepCopy() *BluefieldSoftwareVersions {
	if in == nil {
		return nil
	}
	out := new(BluefieldSoftwareVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEndpointSpec) DeepCopyInto(out *ClusterEndpointSpec) {
	*out = *in
	if in.Keepalived != nil {
		in, out := &in.Keepalived, &out.Keepalived
		*out = new(KeepalivedSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEndpointSpec.
func (in *ClusterEndpointSpec) DeepCopy() *ClusterEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	if in.NodeLabels != nil {
		in, out := &in.NodeLabels, &out.NodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigFile) DeepCopyInto(out *ConfigFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigFile.
func (in *ConfigFile) DeepCopy() *ConfigFile {
	if in == nil {
		return nil
	}
	out := new(ConfigFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerdConfig) DeepCopyInto(out *ContainerdConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerdConfig.
func (in *ContainerdConfig) DeepCopy() *ContainerdConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DMSAddress) DeepCopyInto(out *DMSAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DMSAddress.
func (in *DMSAddress) DeepCopy() *DMSAddress {
	if in == nil {
		return nil
	}
	out := new(DMSAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPU) DeepCopyInto(out *DPU) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPU.
func (in *DPU) DeepCopy() *DPU {
	if in == nil {
		return nil
	}
	out := new(DPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPU) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUAgentConfig) DeepCopyInto(out *DPUAgentConfig) {
	*out = *in
	out.SkipOperations = in.SkipOperations
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUAgentConfig.
func (in *DPUAgentConfig) DeepCopy() *DPUAgentConfig {
	if in == nil {
		return nil
	}
	out := new(DPUAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUAgentSkipOperations) DeepCopyInto(out *DPUAgentSkipOperations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUAgentSkipOperations.
func (in *DPUAgentSkipOperations) DeepCopy() *DPUAgentSkipOperations {
	if in == nil {
		return nil
	}
	out := new(DPUAgentSkipOperations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUCluster) DeepCopyInto(out *DPUCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUCluster.
func (in *DPUCluster) DeepCopy() *DPUCluster {
	if in == nil {
		return nil
	}
	out := new(DPUCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUClusterList) DeepCopyInto(out *DPUClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPUCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUClusterList.
func (in *DPUClusterList) DeepCopy() *DPUClusterList {
	if in == nil {
		return nil
	}
	out := new(DPUClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUClusterSpec) DeepCopyInto(out *DPUClusterSpec) {
	*out = *in
	if in.ClusterEndpoint != nil {
		in, out := &in.ClusterEndpoint, &out.ClusterEndpoint
		*out = new(ClusterEndpointSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.JoinToken != nil {
		in, out := &in.JoinToken, &out.JoinToken
		*out = new(JoinTokenSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUClusterSpec.
func (in *DPUClusterSpec) DeepCopy() *DPUClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DPUClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUClusterStatus) DeepCopyInto(out *DPUClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUClusterStatus.
func (in *DPUClusterStatus) DeepCopy() *DPUClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DPUClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUDevice) DeepCopyInto(out *DPUDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUDevice.
func (in *DPUDevice) DeepCopy() *DPUDevice {
	if in == nil {
		return nil
	}
	out := new(DPUDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUDeviceList) DeepCopyInto(out *DPUDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPUDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUDeviceList.
func (in *DPUDeviceList) DeepCopy() *DPUDeviceList {
	if in == nil {
		return nil
	}
	out := new(DPUDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUDeviceSpec) DeepCopyInto(out *DPUDeviceSpec) {
	*out = *in
	if in.PSID != nil {
		in, out := &in.PSID, &out.PSID
		*out = new(string)
		**out = **in
	}
	if in.OPN != nil {
		in, out := &in.OPN, &out.OPN
		*out = new(string)
		**out = **in
	}
	if in.BMCIP != nil {
		in, out := &in.BMCIP, &out.BMCIP
		*out = new(string)
		**out = **in
	}
	if in.BMCPort != nil {
		in, out := &in.BMCPort, &out.BMCPort
		*out = new(uint32)
		**out = **in
	}
	if in.NumberOfPFs != nil {
		in, out := &in.NumberOfPFs, &out.NumberOfPFs
		*out = new(int)
		**out = **in
	}
	if in.PF0Name != nil {
		in, out := &in.PF0Name, &out.PF0Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUDeviceSpec.
func (in *DPUDeviceSpec) DeepCopy() *DPUDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DPUDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUDeviceStatus) DeepCopyInto(out *DPUDeviceStatus) {
	*out = *in
	if in.PSID != nil {
		in, out := &in.PSID, &out.PSID
		*out = new(string)
		**out = **in
	}
	if in.SerialNumber != nil {
		in, out := &in.SerialNumber, &out.SerialNumber
		*out = new(string)
		**out = **in
	}
	if in.OPN != nil {
		in, out := &in.OPN, &out.OPN
		*out = new(string)
		**out = **in
	}
	if in.BMCIP != nil {
		in, out := &in.BMCIP, &out.BMCIP
		*out = new(string)
		**out = **in
	}
	if in.BMCPort != nil {
		in, out := &in.BMCPort, &out.BMCPort
		*out = new(uint32)
		**out = **in
	}
	if in.PCIAddress != nil {
		in, out := &in.PCIAddress, &out.PCIAddress
		*out = new(string)
		**out = **in
	}
	if in.PF0Name != nil {
		in, out := &in.PF0Name, &out.PF0Name
		*out = new(string)
		**out = **in
	}
	if in.PF0MAC != nil {
		in, out := &in.PF0MAC, &out.PF0MAC
		*out = new(string)
		**out = **in
	}
	if in.SecureBoot != nil {
		in, out := &in.SecureBoot, &out.SecureBoot
		*out = new(SecureBootStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUDeviceStatus.
func (in *DPUDeviceStatus) DeepCopy() *DPUDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DPUDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUDiscovery) DeepCopyInto(out *DPUDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUDiscovery.
func (in *DPUDiscovery) DeepCopy() *DPUDiscovery {
	if in == nil {
		return nil
	}
	out := new(DPUDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUDiscoveryList) DeepCopyInto(out *DPUDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPUDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUDiscoveryList.
func (in *DPUDiscoveryList) DeepCopy() *DPUDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(DPUDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUDiscoverySpec) DeepCopyInto(out *DPUDiscoverySpec) {
	*out = *in
	in.IPRangeSpec.DeepCopyInto(&out.IPRangeSpec)
	out.ScanInterval = in.ScanInterval
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUDiscoverySpec.
func (in *DPUDiscoverySpec) DeepCopy() *DPUDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(DPUDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUDiscoveryStatus) DeepCopyInto(out *DPUDiscoveryStatus) {
	*out = *in
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUDiscoveryStatus.
func (in *DPUDiscoveryStatus) DeepCopy() *DPUDiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(DPUDiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUFLavorSysctl) DeepCopyInto(out *DPUFLavorSysctl) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUFLavorSysctl.
func (in *DPUFLavorSysctl) DeepCopy() *DPUFLavorSysctl {
	if in == nil {
		return nil
	}
	out := new(DPUFLavorSysctl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUFlavor) DeepCopyInto(out *DPUFlavor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUFlavor.
func (in *DPUFlavor) DeepCopy() *DPUFlavor {
	if in == nil {
		return nil
	}
	out := new(DPUFlavor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUFlavor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUFlavorGrub) DeepCopyInto(out *DPUFlavorGrub) {
	*out = *in
	if in.KernelParameters != nil {
		in, out := &in.KernelParameters, &out.KernelParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUFlavorGrub.
func (in *DPUFlavorGrub) DeepCopy() *DPUFlavorGrub {
	if in == nil {
		return nil
	}
	out := new(DPUFlavorGrub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUFlavorList) DeepCopyInto(out *DPUFlavorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPUFlavor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUFlavorList.
func (in *DPUFlavorList) DeepCopy() *DPUFlavorList {
	if in == nil {
		return nil
	}
	out := new(DPUFlavorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUFlavorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUFlavorOVS) DeepCopyInto(out *DPUFlavorOVS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUFlavorOVS.
func (in *DPUFlavorOVS) DeepCopy() *DPUFlavorOVS {
	if in == nil {
		return nil
	}
	out := new(DPUFlavorOVS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUFlavorSpec) DeepCopyInto(out *DPUFlavorSpec) {
	*out = *in
	in.Grub.DeepCopyInto(&out.Grub)
	in.Sysctl.DeepCopyInto(&out.Sysctl)
	if in.NVConfig != nil {
		in, out := &in.NVConfig, &out.NVConfig
		*out = make([]NVConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.OVS = in.OVS
	if in.BFCfgParameters != nil {
		in, out := &in.BFCfgParameters, &out.BFCfgParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigFiles != nil {
		in, out := &in.ConfigFiles, &out.ConfigFiles
		*out = make([]ConfigFile, len(*in))
		copy(*out, *in)
	}
	out.ContainerdConfig = in.ContainerdConfig
	if in.DPUResources != nil {
		in, out := &in.DPUResources, &out.DPUResources
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.SystemReservedResources != nil {
		in, out := &in.SystemReservedResources, &out.SystemReservedResources
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.HostNetworkInterfaceConfigs != nil {
		in, out := &in.HostNetworkInterfaceConfigs, &out.HostNetworkInterfaceConfigs
		*out = make([]NetworkInterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.DPUAgentConfig = in.DPUAgentConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUFlavorSpec.
func (in *DPUFlavorSpec) DeepCopy() *DPUFlavorSpec {
	if in == nil {
		return nil
	}
	out := new(DPUFlavorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUList) DeepCopyInto(out *DPUList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPU, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUList.
func (in *DPUList) DeepCopy() *DPUList {
	if in == nil {
		return nil
	}
	out := new(DPUList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUNode) DeepCopyInto(out *DPUNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUNode.
func (in *DPUNode) DeepCopy() *DPUNode {
	if in == nil {
		return nil
	}
	out := new(DPUNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUNodeList) DeepCopyInto(out *DPUNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPUNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUNodeList.
func (in *DPUNodeList) DeepCopy() *DPUNodeList {
	if in == nil {
		return nil
	}
	out := new(DPUNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUNodeMaintenance) DeepCopyInto(out *DPUNodeMaintenance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUNodeMaintenance.
func (in *DPUNodeMaintenance) DeepCopy() *DPUNodeMaintenance {
	if in == nil {
		return nil
	}
	out := new(DPUNodeMaintenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUNodeMaintenance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUNodeMaintenanceList) DeepCopyInto(out *DPUNodeMaintenanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPUNodeMaintenance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUNodeMaintenanceList.
func (in *DPUNodeMaintenanceList) DeepCopy() *DPUNodeMaintenanceList {
	if in == nil {
		return nil
	}
	out := new(DPUNodeMaintenanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUNodeMaintenanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUNodeMaintenanceSpec) DeepCopyInto(out *DPUNodeMaintenanceSpec) {
	*out = *in
	if in.NodeEffect != nil {
		in, out := &in.NodeEffect, &out.NodeEffect
		*out = new(NodeEffect)
		(*in).DeepCopyInto(*out)
	}
	if in.Requestor != nil {
		in, out := &in.Requestor, &out.Requestor
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUNodeMaintenanceSpec.
func (in *DPUNodeMaintenanceSpec) DeepCopy() *DPUNodeMaintenanceSpec {
	if in == nil {
		return nil
	}
	out := new(DPUNodeMaintenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUNodeMaintenanceStatus) DeepCopyInto(out *DPUNodeMaintenanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeEffectSyncStartTime != nil {
		in, out := &in.NodeEffectSyncStartTime, &out.NodeEffectSyncStartTime
		*out = (*in).DeepCopy()
	}
	if in.MultiDPUOperationsSyncWaitTime != nil {
		in, out := &in.MultiDPUOperationsSyncWaitTime, &out.MultiDPUOperationsSyncWaitTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxUnavailableDPUNodes != nil {
		in, out := &in.MaxUnavailableDPUNodes, &out.MaxUnavailableDPUNodes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUNodeMaintenanceStatus.
func (in *DPUNodeMaintenanceStatus) DeepCopy() *DPUNodeMaintenanceStatus {
	if in == nil {
		return nil
	}
	out := new(DPUNodeMaintenanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUNodeSpec) DeepCopyInto(out *DPUNodeSpec) {
	*out = *in
	if in.NodeRebootMethod != nil {
		in, out := &in.NodeRebootMethod, &out.NodeRebootMethod
		*out = new(NodeRebootMethod)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeDMSAddress != nil {
		in, out := &in.NodeDMSAddress, &out.NodeDMSAddress
		*out = new(DMSAddress)
		**out = **in
	}
	if in.DPUs != nil {
		in, out := &in.DPUs, &out.DPUs
		*out = make([]DPURef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUNodeSpec.
func (in *DPUNodeSpec) DeepCopy() *DPUNodeSpec {
	if in == nil {
		return nil
	}
	out := new(DPUNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUNodeStatus) DeepCopyInto(out *DPUNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DPUInstallInterface != nil {
		in, out := &in.DPUInstallInterface, &out.DPUInstallInterface
		*out = new(string)
		**out = **in
	}
	if in.KubeNodeRef != nil {
		in, out := &in.KubeNodeRef, &out.KubeNodeRef
		*out = new(string)
		**out = **in
	}
	if in.RebootInProgress != nil {
		in, out := &in.RebootInProgress, &out.RebootInProgress
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUNodeStatus.
func (in *DPUNodeStatus) DeepCopy() *DPUNodeStatus {
	if in == nil {
		return nil
	}
	out := new(DPUNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPURef) DeepCopyInto(out *DPURef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPURef.
func (in *DPURef) DeepCopy() *DPURef {
	if in == nil {
		return nil
	}
	out := new(DPURef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUSet) DeepCopyInto(out *DPUSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUSet.
func (in *DPUSet) DeepCopy() *DPUSet {
	if in == nil {
		return nil
	}
	out := new(DPUSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUSetList) DeepCopyInto(out *DPUSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPUSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUSetList.
func (in *DPUSetList) DeepCopy() *DPUSetList {
	if in == nil {
		return nil
	}
	out := new(DPUSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPUSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUSetSpec) DeepCopyInto(out *DPUSetSpec) {
	*out = *in
	in.Strategy.DeepCopyInto(&out.Strategy)
	if in.DPUNodeSelector != nil {
		in, out := &in.DPUNodeSelector, &out.DPUNodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DPUSelector != nil {
		in, out := &in.DPUSelector, &out.DPUSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DPUDeviceSelector != nil {
		in, out := &in.DPUDeviceSelector, &out.DPUDeviceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.DPUTemplate.DeepCopyInto(&out.DPUTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUSetSpec.
func (in *DPUSetSpec) DeepCopy() *DPUSetSpec {
	if in == nil {
		return nil
	}
	out := new(DPUSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUSetStatus) DeepCopyInto(out *DPUSetStatus) {
	*out = *in
	if in.DPUStatistics != nil {
		in, out := &in.DPUStatistics, &out.DPUStatistics
		*out = make(map[DPUPhase]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUSetStatus.
func (in *DPUSetStatus) DeepCopy() *DPUSetStatus {
	if in == nil {
		return nil
	}
	out := new(DPUSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUSetStrategy) DeepCopyInto(out *DPUSetStrategy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdateDPU)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUSetStrategy.
func (in *DPUSetStrategy) DeepCopy() *DPUSetStrategy {
	if in == nil {
		return nil
	}
	out := new(DPUSetStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUSpec) DeepCopyInto(out *DPUSpec) {
	*out = *in
	if in.PCIAddress != nil {
		in, out := &in.PCIAddress, &out.PCIAddress
		*out = new(string)
		**out = **in
	}
	in.NodeEffect.DeepCopyInto(&out.NodeEffect)
	in.Cluster.DeepCopyInto(&out.Cluster)
	if in.SecureBoot != nil {
		in, out := &in.SecureBoot, &out.SecureBoot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUSpec.
func (in *DPUSpec) DeepCopy() *DPUSpec {
	if in == nil {
		return nil
	}
	out := new(DPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUStatus) DeepCopyInto(out *DPUStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OperationalConditions != nil {
		in, out := &in.OperationalConditions, &out.OperationalConditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DPFVersion != nil {
		in, out := &in.DPFVersion, &out.DPFVersion
		*out = new(string)
		**out = **in
	}
	if in.RequiredReset != nil {
		in, out := &in.RequiredReset, &out.RequiredReset
		*out = new(bool)
		**out = **in
	}
	out.Firmware = in.Firmware
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]corev1.NodeAddress, len(*in))
		copy(*out, *in)
	}
	if in.DPUInstallInterface != nil {
		in, out := &in.DPUInstallInterface, &out.DPUInstallInterface
		*out = new(string)
		**out = **in
	}
	if in.PostProvisioningNodeEffect != nil {
		in, out := &in.PostProvisioningNodeEffect, &out.PostProvisioningNodeEffect
		*out = new(bool)
		**out = **in
	}
	if in.AgentLastStartupTime != nil {
		in, out := &in.AgentLastStartupTime, &out.AgentLastStartupTime
		*out = (*in).DeepCopy()
	}
	if in.JoinTokenExpiresAt != nil {
		in, out := &in.JoinTokenExpiresAt, &out.JoinTokenExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.AgentStatus != nil {
		in, out := &in.AgentStatus, &out.AgentStatus
		*out = new(AgentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.SecureBoot != nil {
		in, out := &in.SecureBoot, &out.SecureBoot
		*out = new(SecureBootStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RedfishTaskID != nil {
		in, out := &in.RedfishTaskID, &out.RedfishTaskID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUStatus.
func (in *DPUStatus) DeepCopy() *DPUStatus {
	if in == nil {
		return nil
	}
	out := new(DPUStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUTemplate) DeepCopyInto(out *DPUTemplate) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUTemplate.
func (in *DPUTemplate) DeepCopy() *DPUTemplate {
	if in == nil {
		return nil
	}
	out := new(DPUTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUTemplateSpec) DeepCopyInto(out *DPUTemplateSpec) {
	*out = *in
	out.BFB = in.BFB
	in.NodeEffect.DeepCopyInto(&out.NodeEffect)
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(ClusterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecureBoot != nil {
		in, out := &in.SecureBoot, &out.SecureBoot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUTemplateSpec.
func (in *DPUTemplateSpec) DeepCopy() *DPUTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(DPUTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadedComponents) DeepCopyInto(out *DownloadedComponents) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadedComponents.
func (in *DownloadedComponents) DeepCopy() *DownloadedComponents {
	if in == nil {
		return nil
	}
	out := new(DownloadedComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *External) DeepCopyInto(out *External) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new External.
func (in *External) DeepCopy() *External {
	if in == nil {
		return nil
	}
	out := new(External)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Firmware) DeepCopyInto(out *Firmware) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Firmware.
func (in *Firmware) DeepCopy() *Firmware {
	if in == nil {
		return nil
	}
	out := new(Firmware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GNOI) DeepCopyInto(out *GNOI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GNOI.
func (in *GNOI) DeepCopy() *GNOI {
	if in == nil {
		return nil
	}
	out := new(GNOI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostAgent) DeepCopyInto(out *HostAgent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostAgent.
func (in *HostAgent) DeepCopy() *HostAgent {
	if in == nil {
		return nil
	}
	out := new(HostAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPRange) DeepCopyInto(out *IPRange) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPRange.
func (in *IPRange) DeepCopy() *IPRange {
	if in == nil {
		return nil
	}
	out := new(IPRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPRangeValidationSpec) DeepCopyInto(out *IPRangeValidationSpec) {
	*out = *in
	in.IPRange.DeepCopyInto(&out.IPRange)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPRangeValidationSpec.
func (in *IPRangeValidationSpec) DeepCopy() *IPRangeValidationSpec {
	if in == nil {
		return nil
	}
	out := new(IPRangeValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JoinTokenSpec) DeepCopyInto(out *JoinTokenSpec) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptTemplateRef != nil {
		in, out := &in.ScriptTemplateRef, &out.ScriptTemplateRef
		*out = new(ScriptTemplateRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JoinTokenSpec.
func (in *JoinTokenSpec) DeepCopy() *JoinTokenSpec {
	if in == nil {
		return nil
	}
	out := new(JoinTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sCluster) DeepCopyInto(out *K8sCluster) {
	*out = *in
	in.ClusterSpec.DeepCopyInto(&out.ClusterSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sCluster.
func (in *K8sCluster) DeepCopy() *K8sCluster {
	if in == nil {
		return nil
	}
	out := new(K8sCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeepalivedSpec) DeepCopyInto(out *KeepalivedSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeepalivedSpec.
func (in *KeepalivedSpec) DeepCopy() *KeepalivedSpec {
	if in == nil {
		return nil
	}
	out := new(KeepalivedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVConfig) DeepCopyInto(out *NVConfig) {
	*out = *in
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVConfig.
func (in *NVConfig) DeepCopy() *NVConfig {
	if in == nil {
		return nil
	}
	out := new(NVConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceConfig) DeepCopyInto(out *NetworkInterfaceConfig) {
	*out = *in
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int32)
		**out = **in
	}
	if in.DHCP != nil {
		in, out := &in.DHCP, &out.DHCP
		*out = new(bool)
		**out = **in
	}
	if in.NVConfig != nil {
		in, out := &in.NVConfig, &out.NVConfig
		*out = new(NVConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceConfig.
func (in *NetworkInterfaceConfig) DeepCopy() *NetworkInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEffect) DeepCopyInto(out *NodeEffect) {
	*out = *in
	in.Action.DeepCopyInto(&out.Action)
	in.UpgradePolicy.DeepCopyInto(&out.UpgradePolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEffect.
func (in *NodeEffect) DeepCopy() *NodeEffect {
	if in == nil {
		return nil
	}
	out := new(NodeEffect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRebootMethod) DeepCopyInto(out *NodeRebootMethod) {
	*out = *in
	if in.GNOI != nil {
		in, out := &in.GNOI, &out.GNOI
		*out = new(GNOI)
		**out = **in
	}
	if in.HostAgent != nil {
		in, out := &in.HostAgent, &out.HostAgent
		*out = new(HostAgent)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(External)
		**out = **in
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(Script)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRebootMethod.
func (in *NodeRebootMethod) DeepCopy() *NodeRebootMethod {
	if in == nil {
		return nil
	}
	out := new(NodeRebootMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingNVConfigDevice) DeepCopyInto(out *PendingNVConfigDevice) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]PendingNVConfigEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingNVConfigDevice.
func (in *PendingNVConfigDevice) DeepCopy() *PendingNVConfigDevice {
	if in == nil {
		return nil
	}
	out := new(PendingNVConfigDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingNVConfigEntry) DeepCopyInto(out *PendingNVConfigEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingNVConfigEntry.
func (in *PendingNVConfigEntry) DeepCopy() *PendingNVConfigEntry {
	if in == nil {
		return nil
	}
	out := new(PendingNVConfigEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingNVConfigState) DeepCopyInto(out *PendingNVConfigState) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]PendingNVConfigDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingNVConfigState.
func (in *PendingNVConfigState) DeepCopy() *PendingNVConfigState {
	if in == nil {
		return nil
	}
	out := new(PendingNVConfigState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateDPU) DeepCopyInto(out *RollingUpdateDPU) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateDPU.
func (in *RollingUpdateDPU) DeepCopy() *RollingUpdateDPU {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateDPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Script) DeepCopyInto(out *Script) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Script.
func (in *Script) DeepCopy() *Script {
	if in == nil {
		return nil
	}
	out := new(Script)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptTemplateRef) DeepCopyInto(out *ScriptTemplateRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptTemplateRef.
func (in *ScriptTemplateRef) DeepCopy() *ScriptTemplateRef {
	if in == nil {
		return nil
	}
	out := new(ScriptTemplateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureBootStatus) DeepCopyInto(out *SecureBootStatus) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureBootStatus.
func (in *SecureBootStatus) DeepCopy() *SecureBootStatus {
	if in == nil {
		return nil
	}
	out := new(SecureBootStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TmpFwComponents) DeepCopyInto(out *TmpFwComponents) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TmpFwComponents.
func (in *TmpFwComponents) DeepCopy() *TmpFwComponents {
	if in == nil {
		return nil
	}
	out := new(TmpFwComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TmpFwComponentsVersions) DeepCopyInto(out *TmpFwComponentsVersions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TmpFwComponentsVersions.
func (in *TmpFwComponentsVersions) DeepCopy() *TmpFwComponentsVersions {
	if in == nil {
		return nil
	}
	out := new(TmpFwComponentsVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePolicy) DeepCopyInto(out *UpgradePolicy) {
	*out = *in
	if in.ApplyOnLabelChange != nil {
		in, out := &in.ApplyOnLabelChange, &out.ApplyOnLabelChange
		*out = new(bool)
		**out = **in
	}
	if in.NodeMaintenanceAdditionalRequestors != nil {
		in, out := &in.NodeMaintenanceAdditionalRequestors, &out.NodeMaintenanceAdditionalRequestors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePolicy.
func (in *UpgradePolicy) DeepCopy() *UpgradePolicy {
	if in == nil {
		return nil
	}
	out := new(UpgradePolicy)
	in.DeepCopyInto(out)
	return out
}
